ALTER TABLE "ProductionDetail"
  ADD COLUMN IF NOT EXISTS "transmittedVolume" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "approvalsVolume" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "bookedVolume" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sourceSheet" TEXT,
  ADD COLUMN IF NOT EXISTS "agentLevel" TEXT,
  ADD COLUMN IF NOT EXISTS "dateHired" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "agentType" TEXT,
  ADD COLUMN IF NOT EXISTS "monthlyGoal" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "monthlyActual" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "monthlyAchievement" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "overallGoal" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "overallActual" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "overallAchievement" DOUBLE PRECISION;
