export const SKIP_CONFLICT = "SKIP_CONFLICT";
export const FIELDS = ["campaign", "goalType", "seat", "target", "week1", "week2", "week3", "week4", "week5", "mtd", "achievement", "runRate", "rrAchievement", "workingDays", "daysLapse", "dateUpdated"] as const;
export type Field = typeof FIELDS[number];
export const NUMBER_FIELDS = FIELDS.filter(field => !["campaign", "goalType", "dateUpdated"].includes(field)) as Exclude<Field, "campaign" | "goalType" | "dateUpdated">[];
export type Numbers = Record<typeof NUMBER_FIELDS[number], number | null>;
export type Availability = "AVAILABLE" | "PENDING" | "FORMULA_ERROR" | "INVALID";
export type Classification = "NEW" | "UPDATE" | "DUPLICATE" | "WARNING" | "CONFLICT" | "INVALID" | "PENDING";
export type Issue = { code: string; message: string; field?: string; level: "WARNING" | "ERROR" };
export type RawCell = { address: string; type: string | null; value: string | number | boolean | null; formatted: string | null; formula: string | null; numberFormat: string | null; metadata?: Record<string, unknown> };
export type RawRow = { sourceSheet: string; sourceRow: number; cells: RawCell[] };
export type Column = { index: number; letter: string; header: string; field: Field | null; populatedRows: number };
export type Sheet = { name: string; rows: number; columns: number; headerRow: number | null; detected: boolean; headers: Column[]; warnings: string[]; nonEmptyCells: number; metadata: Record<string, unknown> };
export type Inspection = { fileName: string; fileType: string; fileHash: string; sheets: Sheet[]; nonEmptyCells: number; capturedCells: number; coveragePassed: boolean; warnings: string[]; reportingPeriods: { year: number; month: number }[] };
export type Config = { campaignId: string; goalType: string; label: string; unitType: "COUNT" | "CURRENCY" | "PERCENTAGE" | "RATE" | "SCORE" | "CUSTOM"; calculationMethod: "SUM" | "AVERAGE" | "WEIGHTED_AVERAGE" | "DIRECT_VALUE" | "CUSTOM"; aggregationMethod: "SUM" | "AVERAGE" | "WEIGHTED_AVERAGE" | "DIRECT_VALUE" | "CUSTOM"; goalDirection: "HIGHER" | "LOWER"; decimalPrecision: number; tolerance: number; isPercentage: boolean; isCurrency: boolean; isPrimary: boolean; reviewed: boolean; version: string | null; confidence?: number };
export type ReviewOptions = { selectedSheets: string[]; headerRows: Record<string, number>; columnMappings: Record<string, Record<string, Field | "metadata">>; campaignMappings: Record<string, string>; conflictSelections: Record<string, string>; configs: Record<string, Config>; fallbackMonth: number | null; fallbackYear: number | null };
export type Change = { field: string; oldValue: unknown; newValue: unknown };
export type Candidate = { rowKey: string; sourceSheet: string; sourceRow: number; campaignSource: string; campaignId: string | null; campaignName: string | null; goalType: string; goalLabel: string; reportYear: number | null; reportMonth: number | null; reportDate: string | null; reportStatus: string; sourceDateText: string | null; source: Numbers; calculated: Partial<Numbers>; values: Numbers; availability: Record<string, Availability>; issues: Issue[]; status: Classification; action: "INSERT" | "UPDATE" | "SKIP" | "PENDING" | "BLOCK" | "HISTORY_ONLY"; changes: Change[]; existingId: string | null; existingVersion: string | null; config: Config | null; businessUnitId: string | null; key: string | null; conflictRows: string[]; sourceHash: string };
export type Preview = { id: string; status: string; inspection: Inspection; options: ReviewOptions; records: Candidate[]; configs: Record<string, Config>; campaigns: { id: string; name: string }[]; summary: Record<string, number>; previewHash: string; previousImports: { id: string; fileName: string; createdAt: string; importedBy: { name: string }; status: string }[]; result?: Record<string, number> | null; lastError?: string | null };
export const configKey = (campaignId: string, goalType: string) => JSON.stringify([campaignId, goalType]);
export const rowKey = (sheet: string, row: number) => JSON.stringify([sheet, row]);
export const SUMMARY_UNIT = "CAMPAIGN SUMMARY";
